env:
  browser: true
  es6: true
extends:
  - airbnb
  - prettier
  - prettier/react
  - plugin:jest/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - jest
rules:
  func-names: [2, "as-needed"]
  jsx-a11y/label-has-for:
    - 2
    - required:
        every:
          - id
  jsx-a11y/label-has-associated-control:
    - error
    - required:
        some:
          - nesting
          - id
  no-underscore-dangle:
    - error
    - allow:
        - _typeCheck
  class-methods-use-this:
    - error
    - exceptMethods:
        - _typeCheck
