apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: data-analyzer
spec:
  selector:
    matchLabels:
      app: data-analyzer
  replicas: 1
  template:
    metadata:
      labels:
        app: data-analyzer
    spec:
      containers:
      - name: master
        image: agile-avengers-data-analyzer:dev
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 200Mi
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOSTNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "password"
        - name: KC_HOSTNAME
          value: "keycloak"
