 # Formatting

[tool.black]
line-length = 120
include = '\.py?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | alembic\/env\.py
    | \.git
    | \.vscode
    | __pycache__         
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''