"""updated field in userinfo table

Revision ID: 246c98c4a0e8
Revises: d8ae872c1a34
Create Date: 2023-04-13 18:02:25.011399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246c98c4a0e8'
down_revision = 'd8ae872c1a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debit_card', sa.Column('bank_account_number', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'debit_card', 'bank_account', ['bank_account_number'], ['account_number'])
    op.add_column('user_info', sa.Column('user_name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'user_name')
    op.drop_constraint(None, 'debit_card', type_='foreignkey')
    op.drop_column('debit_card', 'bank_account_number')
    # ### end Alembic commands ###
