"""Recreate schema

Revision ID: cf3d726b8e30
Revises: 
Create Date: 2023-04-19 17:40:23.220749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf3d726b8e30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_info',
    sa.Column('billing_info_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('billing_address', sa.String(length=70), nullable=True),
    sa.Column('postal_code', sa.String(length=8), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('billing_info_id')
    )
    op.create_table('user_info',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=True),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('mobile_number', sa.String(length=10), nullable=True),
    sa.Column('email_id', sa.String(length=30), nullable=True),
    sa.Column('is_merchant', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('bank_account',
    sa.Column('account_number', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('account_holders_name', sa.String(length=30), nullable=True),
    sa.Column('account_balance', sa.FLOAT(), nullable=True),
    sa.Column('bank_name', sa.String(length=30), nullable=True),
    sa.Column('routing_number', sa.String(length=30), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('account_number')
    )
    op.create_table('credit_card',
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('card_network', sa.String(length=30), nullable=True),
    sa.Column('cvv', sa.String(length=30), nullable=True),
    sa.Column('billing_info_id', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.FLOAT(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['billing_info_id'], ['billing_info.billing_info_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('card_number')
    )
    op.create_table('merchant',
    sa.Column('merchant_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sub_category', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_table('debit_card',
    sa.Column('card_number', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('card_network', sa.String(length=30), nullable=True),
    sa.Column('cvv', sa.String(length=30), nullable=True),
    sa.Column('billing_info_id', sa.Integer(), nullable=True),
    sa.Column('bank_account_number', sa.String(length=30), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['bank_account_number'], ['bank_account.account_number'], ),
    sa.ForeignKeyConstraint(['billing_info_id'], ['billing_info.billing_info_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('card_number')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=True),
    sa.Column('payee_id', sa.Integer(), nullable=True),
    sa.Column('transaction_amount', sa.FLOAT(), nullable=True),
    sa.Column('transaction_method', sa.String(length=30), nullable=True),
    sa.Column('transaction_method_id', sa.String(length=30), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=30), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['payee_id'], ['user_info.user_id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['user_info.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('debit_card')
    op.drop_table('merchant')
    op.drop_table('credit_card')
    op.drop_table('bank_account')
    op.drop_table('user_info')
    op.drop_table('billing_info')
    # ### end Alembic commands ###
