"""First commit

Revision ID: d8ae872c1a34
Revises: 46571320c656
Create Date: 2023-04-08 13:16:12.409923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ae872c1a34'
down_revision = '46571320c656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
