version: "3.7"
services:
  frontend:
    image: web_frontend
    container_name: easy_pay_frontend
    user: "1001:1001"
    network_mode: "host"
    deploy:
      restart_policy:
        condition: on-failure
